export const appTabs = [
  {
    nativeName: 'index',
    webName: 'home',
    href: '/',
    label: 'Início',
    emoji: '🏠',
    sf: { default: 'house', selected: 'house.fill' },
    md: { default: 'home', selected: 'home_filled' },
  },
  {
    nativeName: 'catalog',
    webName: 'catalog',
    href: '/catalog',
    label: 'Catálogo',
    emoji: '🗂️',
    sf: { default: 'folder', selected: 'folder.fill' },
    md: { default: 'folder', selected: 'folder' },
  },
  {
    nativeName: 'cart',
    webName: 'cart',
    href: '/cart',
    label: 'Carrinho',
    emoji: '🛒',
    sf: { default: 'cart', selected: 'cart.fill' },
    md: { default: 'shopping_cart', selected: 'shopping_cart' },
  },
  {
    nativeName: 'orders',
    webName: 'orders',
    href: '/orders',
    label: 'Pedidos',
    emoji: '📦',
    sf: { default: 'shippingbox', selected: 'shippingbox.fill' },
    md: { default: 'inventory_2', selected: 'inventory_2' },
  },
  {
    nativeName: 'profile',
    webName: 'profile',
    href: '/profile',
    label: 'Perfil',
    emoji: '👤',
    sf: { default: 'person', selected: 'person.fill' },
    md: { default: 'person', selected: 'person' },
  },
] as const;
