export const Palette = {
  verde50: '#F1FAF3',
  verde100: '#DFF3E6',
  verde200: '#B6E3C4',
  verde400: '#56B876',
  verde500: '#2E9A52',
  verde600: '#1B7A38',
  verde700: '#12602A',
  verde800: '#0A3D1B',
  ambar600: '#E9962A',
  ambarSoft: '#FDF0DC',
  ambarText: '#8A5410',
  terra600: '#8A5A34',
  terraSoft: '#F4EBE3',
  terraText: '#6B4526',
  erro600: '#C8342B',
  erroSoft: '#FBE4E1',
  erroText: '#992019',
  fundo: '#FBFBF9',
  card: '#FFFFFF',
  sunken: '#F5F6F3',
  borda: '#E8E9E4',
  bordaForte: '#D6D8D1',
  texto: '#12151A',
  textoMedio: '#4A5157',
  textoFraco: '#6A7178',
  textoApagado: '#9AA1A6',
} as const;

export const Colors = {
  surface: {
    base: Palette.fundo,
    layer1: Palette.card,
    layer2: Palette.card,
    layer3: Palette.sunken,
    sunken: Palette.sunken,
    brand: Palette.verde800,
    overlay: 'rgba(255, 255, 255, 0.92)',
  },
  accent: {
    primary: Palette.verde600,
    primaryHover: Palette.verde700,
    primaryMuted: Palette.verde100,
    primarySoft: Palette.verde50,
    primaryBorder: Palette.verde200,
    onBrand: Palette.verde200,
  },
  brand: {
    cyan: Palette.verde500,
    cyanMuted: Palette.verde50,
    cyanBorder: Palette.verde200,
  },
  text: {
    primary: Palette.texto,
    secondary: Palette.textoMedio,
    muted: Palette.textoFraco,
    disabled: Palette.textoApagado,
    inverse: '#FFFFFF',
    onBrand: Palette.verde200,
    link: Palette.verde700,
    price: Palette.texto,
    priceOld: Palette.textoApagado,
    discount: Palette.verde700,
  },
  border: {
    subtle: '#F1F1EE',
    default: Palette.borda,
    strong: Palette.bordaForte,
    accent: Palette.verde200,
  },
  feedback: {
    success: Palette.verde600,
    successMuted: Palette.verde100,
    successText: Palette.verde800,
    warning: Palette.ambar600,
    warningMuted: Palette.ambarSoft,
    warningText: Palette.ambarText,
    error: Palette.erro600,
    errorMuted: Palette.erroSoft,
    errorText: Palette.erroText,
    info: Palette.terra600,
    infoMuted: Palette.terraSoft,
    infoText: Palette.terraText,
  },
  category: {
    fertilizante: Palette.verde500,
    defensivo: Palette.ambar600,
    semente: Palette.verde600,
    irrigacao: Palette.verde400,
    maquinario: Palette.textoMedio,
    nutricao: Palette.terra600,
  },
  categorySoft: {
    fertilizante: Palette.verde100,
    defensivo: Palette.ambarSoft,
    semente: Palette.verde100,
    irrigacao: Palette.verde50,
    maquinario: Palette.sunken,
    nutricao: Palette.terraSoft,
  },
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
} as const;
